Add schema for the clinic database
gids-dadi/Vet-clinic-database pull request #7
Opened 2022-08-23 13:13 UTC by gids-dadi

This branch contains:
The schema used to create the clinic database is based on the diagram in the project requirement.
Foreign keys have also been added accordingly.

2022-08-23 14:32 UTC, rloterh requested changes
Hi Gideon & Bruk, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 🚦  

## Highlights 👍  
- Patient and treatment tables properly created


## Required Changes ♻️
_Kindly check the comments under the review._


<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 14:32 UTC, rloterh commented on schema_based_on_diagram.sql
> +    CONSTRAINT fk_patients FOREIGN KEY(patient_id) REFERENCES patients(id),
- [ ] An error is yielding in attempt to create `medical_histories` table referencing `patients` table. You can modify _line 17_ by simply creating a foreign key and reference like this, which works:
```sql
 patient_id integer REFERENCES patients(id),
```
**Create medical_histories table error:**
![image](https://user-images.githubusercontent.com/12745474/186173795-6f0af307-5dee-49a9-985e-2473c23465db.png)

2022-08-23 14:32 UTC, rloterh commented on schema_based_on_diagram.sql
> +);
- [ ] An error is yielding in attempt to create `invoice` table referencing patients `medical_histories`. You can modify _line 27_ by simply creating a foreign key and reference like this, which works:
```sql
 medical_history_id integer REFERENCES medical_histories (id), 
```

**Create invoice table error:**
![image](https://user-images.githubusercontent.com/12745474/186177188-3e9a5648-a50f-4036-8caf-003236a6abb2.png)

2022-08-23 14:32 UTC, rloterh commented on schema_based_on_diagram.sql
> +    CONSTRAINT fk_treatment FOREIGN KEY(treatment_id) REFERENCES treatments (id)
- [ ] There is a  syntax error on line 38. Kindly add a comma (**,**) at the end on the line 38

2022-08-23 14:32 UTC, rloterh commented on schema_based_on_diagram.sql
> +    CONSTRAINT fk_treatment FOREIGN KEY(treatment_id) REFERENCES treatments (id)
- [ ] Unable to create table `invoice items` as foreign keys `invoice_id` and `treatment_id` are not properly pointing the appropriate tables. Kindly follow the reviews examples above on the creating the `medical_histories` table to resolve these errors.

**Creating invoice_item error:**
![image](https://user-images.githubusercontent.com/12745474/186184171-e5a028c4-e330-4614-8da6-f35d2e5b2bd7.png)

2022-08-23 14:32 UTC, rloterh commented on schema_based_on_diagram.sql
> +    CONSTRAINT fk_patients FOREIGN KEY(patient_id) REFERENCES patients(id),
- [ ] Kindly ensure that **all** FOREIGN KEYS have indexes created, e.g 
```sql
CREATE INDEX ON medical_histories (patient_id),
```

2022-08-24 05:57 UTC, mateo951 approved these changes
### Hi @gids-dadi, 

Well done making the required changes 🔥
Your project is complete!  There is nothing else to say other than... it's time to merge it 🐐 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 06:02 UTC, merged